In [20]:
%load_ext autoreload

[01-26 18:57:04][INFO] 2025-01-26 18:57:04.184397
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Examen

## Determinante

In [35]:
%autoreload 2
from src import (
    eliminacion_gaussiana,
    descomposicion_LU,
    resolver_LU,
    matriz_aumentada,
    separar_m_aumentada,
    eliminacion_gaussiana_det,
)

import numpy as np
# ####################################################################

def calc_determinante(A: list[list[float]]) -> float:
    """Función que calcula el determinante de una matriz cuadrada usando eliminación gaussiana.

    ## Parameters
    ``A``: Matriz cuadrada de tamaño n x n.

    ## Return
    ``detA``: Determinante de la matriz A, redondeado a 2 decimales.
    """
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada (n x n)."

    # Aplicar eliminación gaussiana para obtener la matriz triangular superior
    A_triangular = eliminacion_gaussiana_det(A.copy())  # Usamos una copia para no modificar la original

    # Calcular el determinante como el producto de la diagonal
    detA = np.prod(np.diag(A_triangular))

    # Redondear a 2 decimales
    detA_redondeado = round(detA, 2)


    return print(f"Determinante = {detA_redondeado}")



# Ejercicio 1

In [36]:
A1 = [
    [-4, 2, -4, -4, 1, 2, 5, 3, 5, 1],
    [1, 0, 4, 3, 0, -2, 3, 0, 1, 5],
    [5, 5, -4, 5, -4, 2, 2, 2, 4, 4],
    [-1, 3, 4, -1, -4, 0, 5, 0, 0, 5],
    [4, 1, 4, 2, 0, 0, 3, -1, 0, 2],
    [2, -2, 1, -1, -2, -3, 2, -2, 4, -1],
    [3, -2, -3, -2, -1, -3, 5, -1, 5, 0],
    [3, 4, -3, 3, -2, 2, -4, -4, 1, 5],
    [-4, 0, 3, 3, -3, -2, -2, 0, 5, -4],
    [-2, 4, 4, -2, -1, 1, 5, -1, 3, -3],
]
calc_determinante(A1)

Matriz triangular superior después de la eliminación gaussiana:
[[  1.     0.     4.     3.     0.    -2.     3.     0.     1.     5.  ]
 [  0.     1.   -12.   -10.     0.     8.    -9.    -1.    -4.   -18.  ]
 [  0.     0.    19.    15.    -3.   -10.    10.     0.     9.    16.  ]
 [  0.     0.     0.    -0.21  -7.16  -1.53  -1.47  -3.    12.47 -18.16]
 [  0.     0.     0.     0.    21.     0.    19.    11.   -25.    63.  ]
 [  0.     0.     0.     0.     0.    17.   -55.86  -8.29 -55.71 -25.  ]
 [  0.     0.     0.     0.     0.     0.     2.95  -0.12  15.32 -12.06]
 [  0.     0.     0.     0.     0.     0.     0.     1.23  14.62   2.02]
 [  0.     0.     0.     0.     0.     0.     0.     0.    64.7  -27.09]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.    29.44]]
Determinante = -9844877.7


# Ejercicio 2

In [37]:
A2 = [
    [2, 2, 4, 5, -2, -3, 2, -2],
    [-1, -1, 3, 2, 1, 1, -4, 4],
    [2, 5, -3, -3, -2, 2, 5, 3],
    [-2, -4, 0, 1, -1, 5, -4, -1],
    [1, -2, -1, 5, 5, 2, 1, -2],     
    [5, 4, 0, 3, 4, -1, -3, -2],
    [4, -4, 1, 2, 3, 3, -1, 3],
    [-2, 1, -3, 0, 5, 4, 4, -4],
]
calc_determinante(A2)

Matriz triangular superior después de la eliminación gaussiana:
[[ -1.    -1.     3.     2.     1.     1.    -4.     4.  ]
 [  0.    -1.    15.    13.     9.     4.   -23.    18.  ]
 [  0.     0.    10.     9.     0.    -1.    -6.     6.  ]
 [  0.     0.     0.     2.3  -65.   -35.7  102.8  -60.8 ]
 [  0.     0.     0.     0.   -63.43 -28.87  99.83 -48.39]
 [  0.     0.     0.     0.     0.    10.    -5.4    9.2 ]
 [  0.     0.     0.     0.     0.     0.    13.27   9.54]
 [  0.     0.     0.     0.     0.     0.     0.   -12.09]]
Determinante = 2340559.96


# Cambios realizados:

1.- Realice una nueva funcion: *eliminacion_gaussiana_det*, para ir comparando con la original, y evitar perder tiempo.

2.- Con la funcion *eliminacion_gaussiana()* me limite a que solamente llegue hacia transformar la matriz en una triangular superior,
ya que despues de eso comienza la sustitución hacia atrás, y no me sirve esa parte del código.

3.- Una vez que elimine la sustitucion hacia atrás, modifique el return para que retornara la matriz triangular superior.

4.- Tambien modifique el codigo para que solo utilice matrices cuadradas (nxn) y no nx(n+1) como previamente estaba escrita.

5.- Una vez con *eliminacion_gaussiana_det* retornando la matriz triangular superior, solamente me quedo calcular el producto de los elementos 
de su diagonal con:

*Calcular el determinante como el producto de la diagonal*

    detA = np.prod(np.diag(A_triangular))

6- Me tocó realizar un redondeo de los valores con un round, tanto para los valores de la matriz como el valor del determinante.

7.- Se podía realizar un valor absoluto al valor del determinante para que sólo imprima valores positivos pero cómo el valor de un determinante
negativo (Si el determinante es negativo, la orientación del espacio se invierte) podría ser usado en una futura función decidí no hacerlo.

8.- el return print(f"Determinante = {detA_redondeado}") se debe para que no imprima directamente el valor y salga con el tipo de dato np.float64.